### PR TITLE
New Feature: Ability to print based on Package Name

### PR DESCRIPTION
**Pull request by DanPatten**
This is a request for new feature to be added: The ability to print the latest SPDX document based on the original upload package name. This would allow users to retrieve the latest scanned package for a particular package without knowing the ID. The new parameter that has been added is  `--spdxDocName`

   - ***Example:*** `./DoSPDX.py --print TAG --spdxDocName archive.tar.bz2`

If duplicate packages with the same package name exist, then the latest scanned package will be returned.

### CODE REVIEW

**Comment by zwmcfarland** [comment]
You may have to do some more convincing on this one. The original intention of the print functionality was so that a package could be printed from the SOCSDashboard (where the user doesn't need to know the package ID as it is gathered from behind the scenes). 

One common use case is scanning packages across multiple versions. If the package name doesn't change between two versions, but the check-sums do change you will have two records with the same package name. Worst case scenario you will get a result containing information from both records.

This stems from the data base column for package name not having a unique constraint.

**Comment by DanPatten** [comment]
There is another potential solution to this problem. What we are doing is a scan and we immediately need the completed SPDX document back. Right now there is no way to get that back from the database without guessing and if multiple users are using the database I do not want to pull back the last id inserted. Another option would have the program print the spdx id upon completion of a successful scan.

**Comment by zwmcfarland** [comment]
You can can scan and print with a single command line call. Simply pass both the '--scan' and the '--print [format]' parameters.

**Comment by DanPatten** [comment]
In that case this feature is not needed. Thanks.

**Pull request closed without merging**
